### ISSUE TITLE
How to use with NuxtJS?

### ISSUE THREAD

**Issue by ad-on-is** [kyvg/vue3-notification#35]
I'm trying to get this to work with NuxtJS, but I can't figure out why it's not working.

app.vue
```jsx
import Notifications from "@kyvg/vue3-notification";

<template><Notifications /></template>
```

composables/useNotification.ts
```jsx
import { useNotification } from "@kyvg/vue3-notification";

export default useNotification;

```

I always end up getting this error: **Component is missing template or render function.** even thou I can call `useNotification().notify({title: 'foo', text: 'bar'})` without erros or warnings.

**Comment by gabrielphilipes** [comment]
It's not working for me either. Did you find something?

**Comment by ad-on-is** [comment]
Nope!

**Comment by wesnm** [comment]
I'm pretty new to Vue, but I believe the issue here is that this isn't a component but a plugin, so you need to register it in your app instance. In the main.ts/js file, use something like..

```
import Notification from '@kyvg/vue3-notification';

app.use(Notification);
```

On your template, you must refer to the component as `<notifications>`. Lowercase, and plural. That's how the plugin registers itself. It works for me; if there is another way of doing it, I'd love to know because I tried everything else and I only got the same error.

Look at the "demo" directory in the tree, and duplicate how it is set up. Also make sure you have **mitt** and **velocity-animate** installed, as they are unlisted dependencies.

**Comment by kyvg** [comment]
@ad-on-is  You should register as a plugin, but you try to register it as component )

```javascript
import Notification from '@kyvg/vue3-notification'

export default defineNuxtPlugin((nuxtApp) => 
  nuxtApp.vueApp.use(Notification)
)
```

**Comment by ad-on-is** [comment]
> @ad-on-is You should register as a plugin, but you trying to register it as component ) This example works well
> 
> ```js
> // plugins/notification.client.ts
> import Notification from '@kyvg/vue3-notification'
> 
> export default defineNuxtPlugin((nuxtApp) => 
>   nuxtApp.vueApp.use(Notification)
> )
> ```
> 
> ```
> <template>
>   <div>
>     <notifications />
>   </div>
> </template>
> 
> <script setup>
> import { useNotification } from '@kyvg/vue3-notification';
> 
> const {notify} = useNotification()
> 
> onMounted(() => {
>   notify({
>     text: 'test'
>   })
> })
> </script>
> ```

That works! Thanks!

**Comment by simoroma** [comment]
Even doing this I get the following:
```
[Vue warn]: Failed to resolve component: notifications                                                                              11:57:54 AM
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```
This is a warning. But I also have some more issues with the page because of `<notificaitons />`. Is there a way to fix this?
